### ISSUE TITLE
InstanceId displayed in registry and kibana are different

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-console#55] opened 2017-04-11 12:01 UTC
The instanceId displayed in the registry is not the same in jhipster-console.
I'm not sure if it's a normal behavior.

So to confirm that, in `LoggingConfiguration.java`, I used this code:

```java
    public void addLogstashAppender(LoggerContext context) {
        log.info("Initializing Logstash logging");

        LogstashSocketAppender logstashAppender = new LogstashSocketAppender();
        logstashAppender.setName("LOGSTASH");
        logstashAppender.setContext(context);
        String customFields = "{\"app_name\":\"" + appName + "\",\"app_port\":\"" + serverPort + "\"," +
            "\"instance_id\":\"" + instanceId + "\"}";
        log.debug(">>>>>>>>>>>>>> {}", instanceId);
```
I got:
```
x.x.x.x.x.config.LoggingConfiguration    : >>>>>>>>>>>>>> referentiel:93d13e7ea190e1e6cf0e017880728550
```

In the main method, I added:
```java
log.debug("----->>>>>>>>>>>>>>> {}", env.getProperty("eureka.instance.instanceId"));
```
I got:
```
----------------------------------------------------------
	Config Server: 	Connected to the Registry config server! (local)
----------------------------------------------------------
2017-04-11 12:01:01.400 DEBUG 2319 --- [  restartedMain] x.x.x.referentiel.ReferentielApp  : ----->>>>>>>>>>>>>>> referentiel:1edc5154c85e71730ce6acc6bd296a70
```

In jhipster-console, I have: `93d13e7ea190e1e6cf0e017880728550`
And in registry: `1edc5154c85e71730ce6acc6bd296a70`

**Comment by PierreBesson** [comment] 2017-04-11 12:38
Well, it seems here that the one displaying wrong instanceId is the registry not the console. Am I right ?

**Comment by pascalgrimaud** [comment] 2017-04-11 12:42
I think the correct instanceId is from the registry.

It seems like the instanceId is generated 2 times:
- once in LoggingConfiguration -> this value is displayed in the console
- once somewhere else, and the microservice keep this value -> this value is displayed in the registry

Not really major, I just wanted to notice you, @PierreBesson

**Comment by PierreBesson** [comment] 2017-04-11 16:04
@pascalgrimaud I think the problem is the following:

 **application.yml**
```
eureka:
    instance:
        instanceId: testms:${spring.application.instance-id:${random.value}}
```
When no instanceId is available, it will put a random value instead.

**Comment by pascalgrimaud** [comment] 2017-04-11 19:01
@PierreBesson : do you mean I can comment this config ?

**Comment by PierreBesson** [comment] 2017-08-22 11:57
This is finally fixed and merged in the main gen :tada:  !

**Closed by PierreBesson** 2017-08-22 11:57 UTC
